<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Subscriber;
use Doctrine\ORM\EntityRepository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends EntityRepository
{
    /**
     * @return Subscriber[]
     */
    public function findRegistered()
    {
        return $this->findBy(['updatedAt' => null]);
    }
}
